(()=>{'use strict';
const $=id=>document.getElementById(id),BASE='https://andywongpt-my.github.io/off-by/';
let mode='sprint',round=0,targets=[],results=[],start=0,holding=false,locked=false,activeDate='',lastValue=null,lastShareText='';
function localDateKey(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rand(seed){return()=>{seed+=0x6D2B79F5;let t=seed;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function dailyTargets(key){const r=rand(hash('offby-v3-'+key));return[1000,1250+Math.round(r()*500),1750+Math.round(r()*750),2500+Math.round(r()*1000),3500+Math.round(r()*1500)].map(x=>Math.round(x/50)*50)}
function scoreRound(actual,target){return Math.max(0,Math.min(100,Math.round(100-200*Math.abs(actual-target)/target)))}
function best(k){const v=localStorage.getItem(k);return v===null?null:+v}
function query(){const q=new URLSearchParams(location.search),raw=q.get('score');return{mode:q.get('mode'),score:raw===null||raw===''?null:Number(raw),date:q.get('date')}}
function targetDate(){const q=query();return q.mode==='daily'&&/^\d{4}-\d{2}-\d{2}$/.test(q.date||'')?q.date:localDateKey()}
function dateShift(key,delta){const [y,m,d]=key.split('-').map(Number),x=new Date(y,m-1,d);x.setDate(x.getDate()+delta);return localDateKey(x)}
function streakCount(){let days;try{days=JSON.parse(localStorage.getItem('offby_days')||'[]')}catch{days=[]}const set=new Set(days),today=localDateKey();let n=0,key=today;while(set.has(key)){n++;key=dateShift(key,-1)}return n}
function markDailyDone(){let days;try{days=JSON.parse(localStorage.getItem('offby_days')||'[]')}catch{days=[]}if(!days.includes(activeDate))days.push(activeDate);localStorage.setItem('offby_days',JSON.stringify(days.slice(-120)))}
function updateStats(){const d=best('offby_daily'),s=best('offby_sprint');$('bestDaily').textContent=d===null?'—':d+'/100';$('bestSprint').textContent=s===null?'—':s+'ms';$('streak').textContent=streakCount()+'🔥'}
function showChallenge(){const q=query();if(!['sprint','daily'].includes(q.mode)||q.score===null||!Number.isFinite(q.score)){ $('challenge').classList.add('hidden'); return false }$('challenge').classList.remove('hidden');$('challenge').innerHTML=q.mode==='sprint'?`<strong>HEAD-TO-HEAD CHALLENGE</strong>Someone was <b>${q.score} ms off</b>. Beat that.`:`<strong>DAILY FIVE CHALLENGE · ${q.date||'TODAY'}</strong>Someone scored <b>${q.score}/100</b>. Same targets. No excuses.`;setMode(q.mode);return true}
function setMode(m){mode=m;$('dailyTab').classList.toggle('active',m==='daily');$('sprintTab').classList.toggle('active',m==='sprint');startRun()}
function startRun(){round=0;results=[];locked=false;holding=false;lastValue=null;lastShareText='';activeDate=targetDate();targets=mode==='daily'?dailyTargets(activeDate):[1000];$('play').classList.remove('hidden');$('result').classList.add('hidden');renderRound()}
function renderRound(){const t=targets[round];$('setLabel').textContent=mode==='daily'?(activeDate===localDateKey()?"TODAY'S DAILY FIVE":'CHALLENGE · '+activeDate):'ONE SECOND';$('roundLabel').textContent=String(round+1).padStart(2,'0')+' / '+String(targets.length).padStart(2,'0');$('target').textContent=(t/1000).toFixed(3);$('feedback').textContent='The timer is hidden. The pressure is not.';$('hold').textContent='Hold. Then let go.';$('hold').classList.remove('hidden','down');$('next').classList.add('hidden');locked=false;renderDots()}
function renderDots(){$('dots').innerHTML=targets.map((_,i)=>`<i class="dot ${i<results.length?'done':i===round?'now':''}"></i>`).join('')}
function begin(e){if(locked||holding)return;if(e?.type==='keydown'&&(e.repeat||e.code!=='Space'))return;if(e?.type==='keydown')e.preventDefault();holding=true;start=performance.now();$('hold').classList.add('down');$('hold').textContent='Release when it feels right…';$('feedback').textContent='No timer. Trust the weird clock in your head.'}
function cancelHold(){if(!holding)return;holding=false;$('hold').classList.remove('down');$('hold').textContent='Hold. Then let go.';$('feedback').textContent='Attempt cancelled. Try again.'}
function end(e){if(!holding)return;if(e?.type==='keyup'&&e.code!=='Space')return;if(e?.type==='keyup')e.preventDefault();holding=false;locked=true;const actual=Math.round(performance.now()-start),target=targets[round],miss=actual-target;results.push({target,actual,miss,pts:scoreRound(actual,target)});$('hold').classList.remove('down');$('hold').classList.add('hidden');$('feedback').textContent=`${actual} ms — ${miss===0?'EXACT. Somehow.':Math.abs(miss)+' ms '+(miss>0?'late':'early')}.`;renderDots();if(round<targets.length-1)$('next').classList.remove('hidden');else setTimeout(showResult,220)}
function quality(n){if(mode==='sprint'){if(n<=10)return['HUMAN STOPWATCH','Okay, that is annoyingly close.'];if(n<=35)return['CLOCK WHISPERER','You have earned the right to be insufferable about this.'];if(n<=80)return['VERY WELL TIMED','Good enough to immediately challenge somebody.'];if(n<=180)return['SOLID HUMAN','Respectable. Unfortunately, now you have to try again.'];return['TIME IS A CONSTRUCT','Your one second went on a small adventure.']}if(n>=97)return['CLOCK WHISPERER','This is the kind of score people accuse of being lucky.'];if(n>=90)return['DANGEROUSLY TIMED','Post it before your next attempt ruins the evidence.'];if(n>=80)return['VERY SOLID HUMAN','Strong enough to start an argument in the group chat.'];if(n>=65)return['RESPECTABLE CHAOS','Not perfect. Very challengeable.'];return['TIME IS A SUGGESTION','Your internal clock has chosen artistic freedom.']}
function challengeOutcome(value){const q=query();if(q.mode!==mode||q.score===null||!Number.isFinite(q.score))return'';const won=mode==='sprint'?value<q.score:value>q.score,tie=value===q.score;return tie?'🤝 Exact tie. Rematch immediately.':won?'🏆 You beat the challenge. Send the result back.':'😬 They still have you. Hit Rematch.'}
function challengeUrl(value){const u=new URL(BASE);u.searchParams.set('mode',mode);u.searchParams.set('score',String(value));if(mode==='daily')u.searchParams.set('date',activeDate);u.searchParams.set('v','3');return u.toString()}
function shareText(value,url){if(mode==='sprint')return `I was only ${value}ms off exactly one second on OFF BY.\n\nNo timer. No progress bar. Just vibes.\n\nBeat me: ${url}`;const misses=results.map(r=>Math.abs(r.miss)+'ms').join(' · ');return `I scored ${value}/100 on OFF BY.'s Daily Five.\n\n${misses}\n\nSame targets. Think your internal clock is better?\n${url}`}
function showResult(){$('play').classList.add('hidden');$('result').classList.remove('hidden');const misses=results.map(r=>Math.abs(r.miss)),closest=Math.min(...misses),avg=Math.round(misses.reduce((a,b)=>a+b,0)/misses.length);let value;if(mode==='daily'){value=Math.round(results.reduce((a,r)=>a+r.pts,0)/results.length);$('score').textContent=value;$('denom').textContent='/100';$('m1').textContent=avg+' ms';$('m2').textContent=closest+' ms';$('m1l').textContent='AVERAGE MISS';$('m2l').textContent='CLOSEST ROUND';const b=best('offby_daily');if(b===null||value>b)localStorage.setItem('offby_daily',value);if(activeDate===localDateKey())markDailyDone()}else{value=closest;$('score').textContent=value;$('denom').textContent=' ms off';$('m1').textContent=results[0].actual+' ms';$('m2').textContent=(results[0].miss>0?'+':'')+results[0].miss+' ms';$('m1l').textContent='YOUR SECOND';$('m2l').textContent='ERROR';const b=best('offby_sprint');if(b===null||value<b)localStorage.setItem('offby_sprint',value)}lastValue=value;const ql=quality(value);$('stamp').textContent=ql[0];$('resultTitle').textContent=mode==='sprint'?'How expensive is your internal clock?':'Five rounds. One ego.';$('roast').textContent=ql[1];$('rounds').textContent=results.map(r=>(r.miss>=0?'+':'')+r.miss+'ms').join('  ');const outcome=challengeOutcome(value);$('outcome').classList.toggle('hidden',!outcome);$('outcome').textContent=outcome;const url=challengeUrl(value),text=shareText(value,url);lastShareText=text;$('xShare').href='https://twitter.com/intent/tweet?text='+encodeURIComponent(text);$('nativeShare').classList.toggle('hidden',!navigator.share);$('nativeShare').onclick=()=>navigator.share?.({title:'OFF BY.',text:mode==='sprint'?`I was ${value}ms off one second. Beat me.`:`I scored ${value}/100 on OFF BY. Beat me.`,url}).catch(()=>{});$('copy').onclick=()=>copyResult();$('save').onclick=()=>saveCard(value);$('dailyCta').classList.toggle('hidden',mode==='daily');updateStats()}
function toast(s){$('toast').textContent=s;$('toast').classList.add('on');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('on'),1500)}
async function copyResult(){const s=lastShareText;if(!s)return;try{await navigator.clipboard.writeText(s);toast('Result + challenge copied.')}catch{const t=document.createElement('textarea');t.value=s;document.body.append(t);t.select();document.execCommand('copy');t.remove();toast('Result + challenge copied.')}}
function saveCard(value){const c=document.createElement('canvas');c.width=1200;c.height=630;const x=c.getContext('2d');x.fillStyle='#f4f3eb';x.fillRect(0,0,c.width,c.height);x.fillStyle='#f34b27';x.fillRect(70,70,18,18);x.fillStyle='#20221f';x.font='900 62px Arial';x.fillText('OFF BY.',70,150);x.font='700 30px Arial';x.fillText(mode==='sprint'?'ONE SECOND · NO CLOCK':'DAILY FIVE · '+activeDate,72,205);x.font='900 164px monospace';x.fillText(String(value),70,405);x.font='700 42px monospace';x.fillStyle='#74776e';x.fillText(mode==='sprint'?'ms off':'/100',70+(String(value).length*100),404);x.fillStyle='#20221f';x.font='700 27px Arial';x.fillText(mode==='sprint'?'Think your internal clock is better?':'Same five targets. Beat my score.',72,490);x.font='22px monospace';x.fillStyle='#74776e';x.fillText('andywongpt-my.github.io/off-by/',72,548);const a=document.createElement('a');a.download=`off-by-${mode}-${value}.png`;a.href=c.toDataURL('image/png');a.click();toast('Score card saved.')}
$('sprintTab').onclick=()=>setMode('sprint');$('dailyTab').onclick=()=>setMode('daily');$('next').onclick=()=>{round++;renderRound()};$('again').onclick=startRun;$('dailyCta').onclick=()=>setMode('daily');$('hold').addEventListener('pointerdown',begin);window.addEventListener('pointerup',end);window.addEventListener('pointercancel',cancelHold);window.addEventListener('keydown',begin);window.addEventListener('keyup',end);updateStats();if(!showChallenge())setMode('sprint');
})();