create table if not exists public.off_by_attempts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  challenge_date date not null,
  mode text not null check (mode in ('sprint','daily')),
  score integer not null,
  actual_ms integer,
  client_id uuid not null,
  player_tag text not null check (player_tag ~ '^[A-Z0-9_-]{3,16}$'),
  request_fingerprint text,
  constraint off_by_score_range check (
    (mode='sprint' and score between 0 and 5000 and (actual_ms is null or actual_ms between 0 and 10000))
    or
    (mode='daily' and score between 0 and 100 and actual_ms is null)
  )
);

create index if not exists off_by_attempts_board_idx
  on public.off_by_attempts (challenge_date, mode, score, created_at);
create index if not exists off_by_attempts_client_idx
  on public.off_by_attempts (challenge_date, mode, client_id, score);
create index if not exists off_by_attempts_rate_idx
  on public.off_by_attempts (request_fingerprint, created_at desc);

alter table public.off_by_attempts enable row level security;

-- Supabase projects created after May 30, 2026 no longer auto-grant
-- Data API privileges. Keep browsers locked out and explicitly allow only
-- the backend service role used inside the Edge Function.
revoke all on table public.off_by_attempts from public, anon, authenticated;
grant select, insert on table public.off_by_attempts to service_role;
revoke all on sequence public.off_by_attempts_id_seq from public, anon, authenticated;
grant usage, select on sequence public.off_by_attempts_id_seq to service_role;

create or replace function public.off_by_leaderboard(
  p_mode text,
  p_date date,
  p_limit integer default 10
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if p_mode not in ('sprint','daily') then
    raise exception 'invalid mode';
  end if;
  p_limit := greatest(1, least(coalesce(p_limit,10), 25));

  with ranked as (
    select
      client_id, player_tag, score, created_at,
      row_number() over (
        partition by client_id
        order by
          case when p_mode='sprint' then score end asc nulls last,
          case when p_mode='daily' then score end desc nulls last,
          created_at asc
      ) as rn
    from public.off_by_attempts
    where mode=p_mode and challenge_date=p_date
  ),
  best as (
    select client_id, player_tag, score, created_at from ranked where rn=1
  ),
  leaders as (
    select *
    from best
    order by
      case when p_mode='sprint' then score end asc nulls last,
      case when p_mode='daily' then score end desc nulls last,
      created_at asc
    limit p_limit
  )
  select jsonb_build_object(
    'mode', p_mode,
    'date', p_date,
    'participants', (select count(*) from best),
    'leaders', coalesce(
      (select jsonb_agg(jsonb_build_object(
        'client_id', client_id,
        'player_tag', player_tag,
        'score', score
      ) order by
        case when p_mode='sprint' then score end asc nulls last,
        case when p_mode='daily' then score end desc nulls last,
        created_at asc
      ) from leaders),
      '[]'::jsonb
    )
  ) into result;

  return result;
end $$;

revoke all on function public.off_by_leaderboard(text,date,integer) from public, anon, authenticated;
grant execute on function public.off_by_leaderboard(text,date,integer) to service_role;
